<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AbdElRahman" failures="5" tests="6" name="Regression" time="35.339" errors="0" timestamp="2022-01-11T18:11:48 EET">
  <testcase classname="TestCases.a02RegressionRegister" name="regressRegister" time="1.876">
    <failure type="java.lang.AssertionError" message="The specified email already exists">
      <![CDATA[java.lang.AssertionError: The specified email already exists
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at TestCases.a02RegressionRegister.regressRegister(a02RegressionRegister.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- regressRegister -->
  <testcase classname="TestCases.a04ValidateLogin_W_InvalidPass" name="validateLogin_W_InvalidPass" time="1.184">
    <failure type="java.lang.AssertionError" message="Login was unsuccessful. Please correct the errors and try again.
Customer is deleted">
      <![CDATA[java.lang.AssertionError: Login was unsuccessful. Please correct the errors and try again.
Customer is deleted
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at TestCases.a04ValidateLogin_W_InvalidPass.validateLogin_W_InvalidPass(a04ValidateLogin_W_InvalidPass.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateLogin_W_InvalidPass -->
  <testcase classname="TestCases.a05ValidateLogin_W_InvalidUN" name="validateLogin_W_InvalidUN" time="1.168">
    <failure type="java.lang.AssertionError" message="Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect">
      <![CDATA[java.lang.AssertionError: Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at TestCases.a05ValidateLogin_W_InvalidUN.validateLogin_W_InvalidUN(a05ValidateLogin_W_InvalidUN.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateLogin_W_InvalidUN -->
  <testcase classname="TestCases.a07ValidateCouponCode" name="validateCouponCode" time="2.802"/>
  <testcase classname="TestCases.a08ValidateTerms" name="validateTerms" time="2.134">
    <failure type="java.lang.AssertionError" message="Please accept the terms of service before the next step.">
      <![CDATA[java.lang.AssertionError: Please accept the terms of service before the next step.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at TestCases.a08ValidateTerms.validateTerms(a08ValidateTerms.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateTerms -->
  <testcase classname="TestCases.a09ValidateAddress" name="validateAddress" time="4.358">
    <failure type="java.lang.AssertionError" message="Country is required.">
      <![CDATA[java.lang.AssertionError: Country is required.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at TestCases.a09ValidateAddress.validateAddress(a09ValidateAddress.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateAddress -->
</testsuite> <!-- Regression -->
